# Generated by Django 4.1.3 on 2022-11-12 15:01

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True)),
                ('image', models.ImageField(default='image/myimage.jpg', upload_to=backend.models.user_directory_path)),
                ('titleApp', models.CharField(max_length=50)),
                ('shortDescription', models.CharField(max_length=50)),
                ('longDescription', models.CharField(max_length=160)),
                ('githubLink', models.CharField(max_length=200)),
                ('youtubeLink', models.CharField(max_length=200)),
                ('launchLink', models.CharField(max_length=200)),
            ],
        ),
    ]
