# Generated by Django 4.1.3 on 2022-12-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_datacard_apptype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacard',
            name='appType',
            field=models.CharField(choices=[('web', 'Web development'), ('mobile', 'Mobile development'), ('ml', 'Machine Learning'), ('ta', 'Task Automatization')], default='web', max_length=20),
        ),
    ]
